=== adithkkn/WSD_LAB_05_DOM_PARSER/Railway.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Railway">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="BookingAndPayments">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="trainno" type="xs:unsignedShort" />
              <xs:element name="seatno" type="xs:unsignedByte" />
              <xs:element name="passengername" type="xs:string" />
              <xs:element name="source" type="xs:string" />
              <xs:element name="destination" type="xs:string" />
              <xs:element name="bookingstatus" type="xs:string" />
              <xs:element name="stationCode" type="xs:unsignedShort" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== adithkkn/WSD_LAB_05_DOM_PARSER/Railway.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Railway.xsl"?>
<Railway xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="Railway.xsd">

   <BookingAndPayments>
      <trainno>1236</trainno>
      <seatno>24</seatno>
      <passengername>govind</passengername>
      <source>Bengaluru</source>
      <destination>kolkata</destination>
      <bookingstatus>successful</bookingstatus>
      <stationCode>1565</stationCode>
   </BookingAndPayments>

<BookingAndPayments>
      <trainno>1246</trainno>
      <seatno>4</seatno>
      <passengername>aravind</passengername>
      <source>kollam</source>
      <destination>kolkata</destination>
      <bookingstatus>successful</bookingstatus>
      <stationCode>15635</stationCode>
   </BookingAndPayments>


   <BookingAndPayments>
      <trainno>1276</trainno>
      <seatno>98</seatno>
      <passengername>kumar</passengername>
      <source>delhi</source>
      <destination>agra</destination>
      <bookingstatus>successful</bookingstatus>
      <stationCode>9874</stationCode>
   </BookingAndPayments>


   <BookingAndPayments>
      <trainno>1230</trainno>
      <seatno>64</seatno>
      <passengername>basil</passengername>
      <source>kottayam</source>
      <destination>kolkata</destination>
      <bookingstatus>successful</bookingstatus>
      <stationCode>1905</stationCode>
   </BookingAndPayments>


   <BookingAndPayments>
      <trainno>1409</trainno>
      <seatno>40</seatno>
      <passengername>kumar</passengername>
      <source>Bengaluru</source>
      <destination>kannur</destination>
      <bookingstatus>successful</bookingstatus>
      <stationCode>1985</stationCode>
   </BookingAndPayments>

   <BookingAndPayments>
      <trainno>8536</trainno>
      <seatno>76</seatno>
      <passengername>jomal</passengername>
      <source>kochi</source>
      <destination>kanyakumari</destination>
      <bookingstatus>successful</bookingstatus>
      <stationCode>9365</stationCode>
   </BookingAndPayments>


   <BookingAndPayments>
      <trainno>1876</trainno>
      <seatno>54</seatno>
      <passengername>shami</passengername>
      <source>Bengaluru</source>
      <destination>chennai</destination>
      <bookingstatus>successful</bookingstatus>
      <stationCode>1974</stationCode>
   </BookingAndPayments>
   

   <BookingAndPayments>
      <trainno>1940</trainno>
      <seatno>34</seatno>
      <passengername>haridoss</passengername>
      <source>madurai</source>
      <destination>mangalore</destination>
      <bookingstatus>successful</bookingstatus>
      <stationCode>8731</stationCode>
   </BookingAndPayments>


   <BookingAndPayments>
      <trainno>1096</trainno>
      <seatno>84</seatno>
      <passengername>david</passengername>
      <source>Bengaluru</source>
      <destination>mumbai</destination>
      <bookingstatus>successful</bookingstatus>
      <stationCode>7565</stationCode>
   </BookingAndPayments>

</Railway>
